name: padi_parking
description: Mobile application developed to speed up the parking service..

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  flutter_facebook_login: ^3.0.0
  pretty_qr_code: ^1.0.2
  firebase_database: ^6.1.2
  path_provider: ^2.0.1
  provider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/parking.png
    - assets/low-shape.png
    - assets/high-shape.png
    - assets/PaDi-logo.png
    - assets/logo.png
    - assets/qr.png
    - assets/alfiler.png
    - assets/visa.png
    - assets/paypal.png
    - assets/master.png
    - assets/avatar.png
    - assets/tache.png
    - assets/tarjeta.png
    - assets/user.png
    - assets/search.png
    - assets/facebook.png
    - assets/androidLoading.gif
    